### PR TITLE
Lagom Pac4j Demo Java

### PR DESCRIPTION
**Pull request by ihostage**
Moved demo from archived https://github.com/lagom/lagom-recipes. Details in this topic https://discuss.lightbend.com/t/recipes-evolving-into-samples/4086

Sorry, @leleuj! 🙏 
Can you rename this repo to `lagom-pac4j-java-demo` and create another one `lagom-pac4j-scala-demo`? I forget, that we have a two recipe for Lagom 😂

### CODE REVIEW

**Comment by leleuj** [comment]
Excellent! A demo will really help people getting in with the Lagom pac4j support.

**Comment by ihostage** [comment]
@leleuj Jerome? 😄 

> Can you rename this repo to lagom-pac4j-java-demo and create another one lagom-pac4j-scala-demo? I forget, that we have a two recipe for Lagom 😂

**Comment by leleuj** [comment]
No problem. Done. You should have receive an invitation for the new repo...

**Comment by ihostage** [comment]
Thanks a lot! 👍

**Pull request merged**
